### ISSUE TITLE
quit

### ISSUE THREAD

**Issue by gilescope** [matheuslessarodrigues/verco#1]
Ctrl-c didn't seem to quit? I tried 'q' as well.

Is this Hotel California? :-)

I find tig really good for staging / unstaging files, but tig doesn't have multiple select. Maybe spacebar to select/unselect a file?

The project seems promising - I like tig but it could be snappier.

**Comment by vamolessa** [comment]
What OS were you using? Which shell?
If you're trying to commit just a couple of files, you can do `cs` that will commit only selected files. You select them with space bar.

Thanks for checking verco out :)

**Comment by gilescope** [comment]
I’m rocking NixOs with fish on a Macbook pro. That’s got to be pretty standard these days right? ;-) 

Hm you’re using the ctrlc crate so I might have found them a bug. Might be nice to map q to quit anyhow. Ok let me try this from bash, it might all work better.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vamolessa** [comment]
I have only access to windows. Maybe it's really a ctrlc issue. Could you try upgrading it and see if it fixes it?

On the other hand, we can make `q` quit the application as well.
Will include it on the next release.

**Comment by gilescope** [comment]
I remapped some keys and I think the code is not taking account of that remapping. Maybe there's a higher abstraction that would take that into effect. Option-C works.

**Comment by vamolessa** [comment]
you mean verco code or ctrlc crate code?

**Comment by gilescope** [comment]
Works in verco. It would be a lot faster to navigate if you can keep the commands to one keystoke so that you didn’t need to press enter. That would make it feel really snappy.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vamolessa** [comment]
wait, you're saying that in order to, say, open help, you need to press `h` and then `enter`?
the intended behaviour should be just pressing `h`.

the input is read using `TerminalInput::read_char()`
maybe updating `crossterm` would help?

could you confirm that in the latest `crossterm` version in your setup, reading a char just needs a single keypress and not an extra `enter` press.

thanks!
