### ISSUE TITLE
Use rustfmt on the project

### ISSUE THREAD

**Issue by Alphare** [matheuslessarodrigues/verco#14]
This is to reduce diff size and keep everything clean. 

I vote for using 80 characters per line because it fits nicely in all the UIs I use, but that's your call.

**Comment by Alphare** [comment]
Ironically, I have a great solution for preventing merge issues in Mercurial by using [format-source](https://foss.heptapod.net/mercurial/format-source), but it seems I have no choice but to re-format every PR.

**Comment by vamolessa** [comment]
will run rustfmt before pushes
