### ISSUE TITLE
Allow lazy loading of log during scroll

### ISSUE THREAD

**Issue by Alphare** [matheuslessarodrigues/verco#17]
This issue is twofold:

- Like THG and many other VCS UIs, Verco should fill the log pane with as much as needed from the VCS and not just an arbitrary default number (50). Maybe the `lc` command should remain, as people might find that useful?
- The log view should be scrollable, with the VCS being queried lazily in the background (maybe some margin already preloaded to reduce waiting time) to update the newly visible entries.

This ties into #8, as I don't believe this would be a lot easier to achieve in an async context by leveraging the built-in pager.

**Comment by vamolessa** [comment]
implemented on `6.2.0`!
