### ISSUE TITLE
Investigate using JSON output from VCS

### ISSUE THREAD

**Issue by Alphare** [matheuslessarodrigues/verco#24]
Mercurial has had a JSON template output since version 3.1. Using that then generating the graph in Rust could allow for a more robust and flexible log for example. (I know that there are ways of doing so with Git too)

This could be used to facilitate a selection interface, merging caches, customizing the output, etc..

**Comment by vamolessa** [comment]
We're now parsing log entries instead of just printing them.
So I'll close this for now but feel free to re-open if there's more to consider.
